import type { Metadata } from "next";
import { getData } from "@/lib/util/sanity";
import Playlist from "../components/Playlist";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const query = await getData(`{
      'data':*[_type=='settings'][0]{feat[]->{title,client,abbr,"slug":slug.current,copy,loop{"image":image.asset->url, "vid":video.asset->playbackId, "ratio":video.asset->data.aspect_ratio}}}
      }`)
  const { data } = query.data
  return (
    <div>
      {children}
      <Playlist data={data.feat} />
    </div>
  );
}
