import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SmoothScrolling from "@/lib/util/SmoothScrolling";
import LogoScroll from "./components/logoScroll";
import Grid from "./components/grid";
import { getData } from "@/lib/util/sanity";
import WorkGrid from "./components/workGrid";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const query = await getData(`{
      'data':*[_type=='settings'][0]{feat[]->{title,client,abbr,"slug":slug.current,copy,loop{"image":image.asset->url, "vid":video.asset->playbackId, "ratio":video.asset->data.aspect_ratio}}}
      }`)
  const { data } = query.data
  return (
    <html lang="en"
    >

      <SmoothScrolling>

        <body className="min-h-screen w-screen  bg-(--black)">
          <Grid />
          <div className="nav absolute top-0 left-0 h-screen w-screen pointer-events-none flex items-center z-50">
            <div className="w-screen h-auto logoHold">
              <LogoScroll time={20} />
            </div>
          </div>
          {children}
        </body>
      </SmoothScrolling>
    </html>
  );
}
