import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SmoothScrolling from "@/lib/util/SmoothScrolling";
import Nav from "./components/nav";
import Grid from "./components/grid";
import { getData } from "@/lib/util/sanity";
import WorkGrid from "./components/workGrid";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const query = await getData(`{
      'data':*[_type=='settings'][0]{feat[]->{title,client,abbr,"slug":slug.current,copy,loop{"image":image.asset->url, "vid":video.asset->playbackId, "ratio":video.asset->data.aspect_ratio}}}
      }`)
  const { data } = query.data
  return (
    <html lang="en"
    >

      <SmoothScrolling>

        <body className="min-h-screen w-screen  bg-(--black)">
          <Grid />
          <Nav />
          {children}
        </body>
      </SmoothScrolling>
    </html>
  );
}
